---
- name: OVA DEPLOYMENTS
  hosts: eur
  gather_facts: false
  become: true
  collections:
    - community.vmware

  vars_files:
    - vars_eur_vms.yml

  tasks:
    - name: Powering Up
      set_fact:
        regvms: "{{ ovavms1 | list + isovms2 | list + ovavms3 | list + ovavms4 | list }}"

    - name: Power Up VMs
      vmware.vmware.vm_powerstate:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        datacenter: "ha-datacenter"
        validate_certs: no
        name: "{{ item.ovaname1 | default(item.isoname2) | default(item.ovaname3) | default(item.ovaname4) }}"
        state: powered-on
      loop: "{{ regvms }}"
      become: true
      delegate_to: localhost
